Add database tests on ALP
os-autoinst/opensuse-jobgroups pull request #197
Opened 2022-09-13 09:01 UTC by Zaoliang

see https://progress.opensuse.org/issues/115196
after merge of https://progress.opensuse.org/issues/115196 setting in job groub or in testsuite on O3 YAML_SCHEDULE: 'schedule/alp/alp_databases.yaml' can be added.

2022-09-14 09:47 UTC, foursixnine requested changes

2022-09-14 09:47 UTC, foursixnine commented on job_groups/alp_poc.yaml
> +    version: '0.1'
this is not needed, as we're only enabling testsuites.

2022-09-14 10:43 UTC, foursixnine commented
PR is related https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15513

2022-09-16 11:02 UTC, Zaoliang commented on job_groups/alp_poc.yaml
> +    version: '0.1'
updated now, thanks

2022-09-16 11:03 UTC, Zaoliang commented
http://10.162.30.85/tests/5026# should be an example for database tests on ALP.

2022-09-16 11:06 UTC, foursixnine approved these changes

2022-09-16 11:07 UTC, foursixnine commented
@Zaoliang you need to solve the conflict first :)

2022-09-16 12:51 UTC, closed without merging