Use 2GB RAM for all Leap 15.4 upgrade tests
os-autoinst/opensuse-jobgroups pull request #216
Opened 2022-10-17 07:41 UTC by rfan1

poo#118357
We may need 2GB RAM size for upgrade tests to to avoid stalls

2022-10-18 06:05 UTC, michaelgrifalconi commented
Hello, maybe the full link of the progress issue https://progress.opensuse.org/issues/118357 is nicer, so people can easily jump to it.
Apart from that, LGTM :)

2022-10-18 07:59 UTC, okurz requested changes
There are already explicit machine definitions like "64bit-2G" on https://openqa.opensuse.org/admin/machines so there should be no need to manually tinker with the memory in all those cases.

2022-10-18 08:55 UTC, rfan1 commented
> There are already explicit machine definitions like "64bit-2G" on https://openqa.opensuse.org/admin/machines so there should be no need to manually tinker with the memory in all those cases.

Thanks @okurz, fixed as your suggestion, please help review again.

2022-10-18 09:00 UTC, pdostal approved these changes

2022-10-18 13:52 UTC, grisu48 approved these changes

2022-10-18 19:56 UTC, okurz approved these changes

2022-10-19 07:14 UTC, foursixnine approved these changes

2022-10-19 07:14 UTC, merged