Move 2 virtualization tests to TW job group for daily review from development group
os-autoinst/opensuse-jobgroups pull request #274
Opened 2023-02-16 11:41 UTC by Julie-CAO

They are two tests from virtualization qa team with ipmi backends. 

- related ticket: https://progress.opensuse.org/issues/103742

The two latest runs:
https://openqa.opensuse.org/tests/3122754    //Failed due to unstable download.opensuse.org
https://openqa.opensuse.org/tests/3122755    //PASS

@alice-suse @xguo @waynechen55 @nanzhg @tbaev @RoyCai7 @varunkojha and O3 maintainers, Welcome review!

2023-02-16 12:18 UTC, DimStar77 commented
I veto:

1) https://openqa.opensuse.org/tests/3122754#next_previous
2) https://openqa.opensuse.org/tests/3122755#next_previous

What's the point of throwing tests that barely pass onto my queue?

2023-02-16 12:45 UTC, Julie-CAO commented
The pass rate is not so low.  The PR was merged yesterday, https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16249. It will make the test more stable. 
With this PR, I guess the tests will get 70% pass rate. The remained 30% failure will result from timeout when fetching files from download.opensuse.org, which I can do little from my end. But I will continue to improve the tests by adding more retries in test scripts or other feasible ways.

2023-02-16 13:43 UTC, sysrich commented
That's still not good enough for the main openSUSE Tumbleweed product job group..do you really expect @DimStar77 and I to spend our days watching these tests restarting them 30% of the time in order to release Tumbleweed every day?

2023-02-16 13:54 UTC, okurz commented
I suggest for a pass rate of about 98%, that should be maintainable

2023-02-16 13:55 UTC, okurz requested changes
I suggest for a pass rate of about 98%, that should be maintainable

2023-02-16 15:25 UTC, DimStar77 commented
> I suggest for a pass rate of about 98%, that should be maintainable

i'd already accept a 85.714285% success rate (1 fail in 7 - so once a week), preferably 96.4285% (1 fail in 28 - once every two weeks)

for a 98% success rate, you need to stay in devel for at least 50 days after a failure - that might be a bit too slow for development

(yes, we unfortunately do have tests that do not meet that rate at the moment)

2023-02-17 03:40 UTC, alice-suse commented
@DimStar77  @sysrich  @okurz  Hello guys, thanks for the review. I agree that it will be better to increase the pass ratio before moving to official job group. 

As @Julie-CAO  mentioned, the remained 30% failure will result from timeout when fetching files from download.opensuse.org, which she can do little. More discussions for the failures by O3 infra poor performance, can be seen in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16249#discussion_r1098128816.  

Can we ask you for a favor to help driving fix for the infra issue in https://progress.opensuse.org/issues/123328? Otherwise it will be difficult for us to deploy virtualization test for Tumbleweed, which should be an important function area for it.

2023-02-17 07:36 UTC, okurz commented
I see https://progress.opensuse.org/issues/123328 actively discussed. I don't think I can add more help there. I observe problems with accessing the openSUSE repos even if it's just on my manually maintained machines so I understand how tests can also be impacted by that. On the other hand the Tumbleweed openQA tests shouldn't be impacted by that when using proper repos from openqa.opensuse.org. Tests mentioned in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16249 like https://openqa.opensuse.org/tests/3049532#step/switch_to_ssh_and_install_hypervisor/18 show downloads from download.opensuse.org which IMHO is wrong in this context. Other tests remove repos pointing to download.opensuse.org, e.g. as in https://openqa.opensuse.org/tests/3123920#step/zypper_clear_repos/6, and add according repos pointing to o3 like in https://openqa.opensuse.org/tests/3123920#step/zypper_ar/4 . I am sure this will alleviate a lot of "zypper download problems"

2023-02-17 10:00 UTC, Julie-CAO commented
> Other tests remove repos pointing to download.opensuse.org, e.g. as in https://openqa.opensuse.org/tests/3123920#step/zypper_clear_repos/6, and add according repos pointing to o3 like in https://openqa.opensuse.org/tests/3123920#step/zypper_ar/4 . I am sure this will alleviate a lot of "zypper download problems"

Thank you, Oliver. I will have a try to install guests with install medium in O3 repo instead of download.opensuse.org. Most of failures after my PR are caused by timeout of dowloading initrd when installing a vm guest.

2023-02-20 01:01 UTC, Julie-CAO commented
Let me fix more issues firstly before adding theses tests to daily review.

2023-10-31 05:20 UTC, Julie-CAO commented
Varun has another ticket to address these two tests. Closing this PR.

2023-10-31 05:20 UTC, closed without merging