Move 2 virtualization tests from Development Tumbleweed Job group to openSUSE Tumbleweed Job group for daily review
os-autoinst/opensuse-jobgroups pull request #368
Opened 2023-09-11 12:33 UTC by varunkojha

Description
-- To add "[virtualization][factory-first] deploy guest installation tests" to the "O3 official job group" due to their consistently high pass ratio.
-- They are two tests from the virtualization [qe-virt] team with IPMI backends.
-- Tests 
- virt-guest-installation-kvm@64bit-ipmi
- virt-guest-installation-xen@64bit-ipmi

- Related ticket: https://progress.opensuse.org/issues/103742
- Latest runs: [KVM](https://openqa.opensuse.org/tests/3564956) and [XEN](https://openqa.opensuse.org/tests/3566381) (Fails due to [BUG](https://bugzilla.suse.com/show_bug.cgi?id=1212132))

2023-09-11 13:59 UTC, okurz requested changes
I don't see the "consistently high pass ratio" yet. In https://openqa.opensuse.org/tests/3562648#step/ipxe_install/19 your first job scenario failed. Can you clarify what happened there? What pass ratio did you calculate? And for the Xen scenario the referenced bug is https://bugzilla.suse.com/show_bug.cgi?id=1212132 with "Normal" severity and not marked as Blocker bug. I suggest to either implement a workaround for that bug or make sure that this bug will soon be worked on to not add failing tests to a validation job group which are unlikely to turn passed anytime soon.

2023-09-12 08:26 UTC, varunkojha commented
> I don't see the "consistently high pass ratio" yet. In https://openqa.opensuse.org/tests/3562648#step/ipxe_install/19 your first job scenario failed. Can you clarify what happened there? What pass ratio did you calculate? And for the Xen scenario the referenced bug is https://bugzilla.suse.com/show_bug.cgi?id=1212132 with "Normal" severity and not marked as Blocker bug. I suggest to either implement a workaround for that bug or make sure that this bug will soon be worked on to not add failing tests to a validation job group which are unlikely to turn passed anytime soon.

I understand your concern Oliver
Marked the bug as a blocker and we will ask to drive the fix.
For the failed test mentioned, I added a comment, that it did not boot from PXE and ipxe install did not happen. 
We can wait for a high enough pass ratio.
In the past 20-25 tests 4 failed at unified_guest_installation due to [Nvidia_repoBUG](https://bugzilla.suse.com/show_bug.cgi?id=1214592) [resolved], rest passed. So I wanted to move to the TW job group.

2023-09-12 10:55 UTC, okurz commented
My general recommendation is to aim for a fail ratio of < 1.00%, so less than 1/100 tests failing due to false positives.

2023-09-18 06:48 UTC, alice-suse commented
> My general recommendation is to aim for a fail ratio of < 1.00%, so less than 1/100 tests failing due to false positives.

@okurz  Thanks for the review. I have to say that's ideal case. Practically, let's apply >6/7 pass ratio, which @DimStar77  agreed in https://github.com/os-autoinst/opensuse-jobgroups/pull/274, especially that at the moment there is NUE1 lab move and the new setup and infra changes of PRG Colo 2 where our test machines are in.

2023-09-18 09:27 UTC, okurz approved these changes

2023-09-20 05:16 UTC, alice-suse approved these changes
LGTM

2023-09-20 05:17 UTC, alice-suse commented
@DimStar77  Hello Dominique, would you please give it a review? If you agree, we'd like to merge it. Thanks!

2023-09-20 05:58 UTC, nanzhg commented
@varunkojha can you pls fix the warning from github checks?

```
Check warning on line 940 in job_groups/opensuse_tumbleweed.yaml

GitHub Actions  / static-check
940:14 [comments] missing starting space in comment
```

2023-09-20 06:31 UTC, varunkojha commented
> @varunkojha can you pls fix the warning from github checks?
> 
> ```
> Check warning on line 940 in job_groups/opensuse_tumbleweed.yaml
> 
> GitHub Actions  / static-check
> 940:14 [comments] missing starting space in comment
> ```

Sure Nan, Done :)

2023-09-22 07:42 UTC, merged